In [1]:
import numpy as np
import sympy as sp
import scipy as sc
from scipy.optimize import fmin

In [2]:
def f(x1, x2, x3):
    return (1/2)*(x1**4)-(x1*x2)+(x2**2)+(x2*x3)+(x3**2)
                       
# Define symbols
x1, x2, x3 = sp.symbols('x1 x2 x3')

# Define the function symbolically
f_sym = f(x1, x2, x3)

# Compute partial derivatives symbolically
df_dw_sym1 = sp.diff(f_sym, x1)
df_db_sym2 = sp.diff(f_sym, x2)
df_db_sym3 = sp.diff(f_sym, x3)

print(df_dw_sym1)
print(df_db_sym2)
print(df_db_sym3)

2.0*x1**3 - x2
-x1 + 2*x2 + x3
x2 + 2*x3


In [26]:
"""These functions determine the argmin for each of the variables in functions f"""

#The problem with the derivation of the first gradient is that if you want to find x1 sucht that it has the lowest value.
#It has a problem when x2 is smaller than zero, because then it has to take the square root of a negative number.
#I have no idea how to solve this except for skipping the calculation of x1 when x2 is negative.
#Therefore I defined two functions. One with correction and one without.
def argmin_x1(x):
    print(f"                    value f before changing x1 is {function(x)}") 
    x1 = (x[1]/2)**(1/3)
    print(f"                    x1 is changed from {x[0]} to {x1}") 
    return x1

def argmin_x1_with_correction(x):
    print(f"                    value f before changing x1 is {function(x)}") 
    if x[1]<0:
        x1 = x[0]
    else:
        x1 = (x[1]/2)**(1/3)
    print(f"                    x1 is changed from {x[0]} to {x1}") 
    return x1

def argmin_x2(x):
    print(f"                    value f before changing x2 is {function(x)}")
    x2 = (x[0]/2)-(x[2]/2)
    print(f"                    x2 is changed from {x[1]} to {x2}") 
    return x2

def argmin_x3(x):
    print(f"                    value f before changing x3 is {function(x)}")
    x3 = (-x[1]/2)
    print(f"                    x3 is changed from {x[2]} to {x3}") 
    return x3

argmin = np.array([argmin_x1, argmin_x2, argmin_x3])
argmin_with_correction = np.array([argmin_x1_with_correction, argmin_x2, argmin_x3])

In [27]:
def function(x):
    return (1/2)*(x[0]**4)-(x[0]*x[1])+(x[1]**2)+(x[1]*x[2])+(x[2]**2)

In [28]:
def coordinate_descent(f, argmin, x_0, max_iter=100):
    t = 0 
    x_t = x_0              
    while t <= max_iter:
        print()
        x_t[0] = argmin[0](x_t)
        x_t[1] = argmin[1](x_t)
        x_t[2] = argmin[2](x_t)
        value_f = f(x_t)
        print(f"After iteration 1, the value of f is{value_f} and x = {x_t}")
        t += 1
    return x_t

Excercise 1:

In [29]:
#answer with the written functions
xex1 = np.array([2, 3, 4])
print(f"arg min for x1 is {argmin_x1(xex1)}")
print(f"arg min for x2 is {argmin_x2(xex1)}")
print(f"arg min for x3 is {argmin_x3(xex1)}")

#test answers
def f1(x):
    return (1/2)*(x[0]**4)-(x[0]*3)+(3**2)+(3*4)+(4**2)
def f2(x):
    return (1/2)*(2**4)-(2*x[1])+(x[1]**2)+(x[1]*4)+(4**2)
def f3(x):
    return (1/2)*(2**4)-(2*3)+(3**2)+(3*x[2])+(x[2]**2)
print(fmin(f1, np.array([2, 3, 4])))
print(fmin(f2, np.array([2, 3, 4])))
print(fmin(f3, np.array([2, 3, 4])))

                    value f before changing x1 is 39.0
                    x1 is changed from 2 to 1.1447142425533319
arg min for x1 is 1.1447142425533319
                    value f before changing x2 is 39.0
                    x2 is changed from 3 to -1.0
arg min for x2 is -1.0
                    value f before changing x3 is 39.0
                    x3 is changed from 4 to -1.5
arg min for x3 is -1.5
Optimization terminated successfully.
         Current function value: 34.424393
         Iterations: 44
         Function evaluations: 86
[1.1446963  3.32945184 4.40781289]
Optimization terminated successfully.
         Current function value: 23.000000
         Iterations: 51
         Function evaluations: 98
[ 2.71250032 -0.9999739   5.10013238]
Optimization terminated successfully.
         Current function value: 8.750000
         Iterations: 52
         Function evaluations: 99
[ 2.69889478  3.81861931 -1.50002244]


Excercise 2:

In [32]:
#answer constructed with the written coordinate_descent function
x_0 = np.array([2,3,4])
print(coordinate_descent(function, argmin_with_correction, x_0))

#testing the results
print(fmin(function, np.array([2, 3, 4]), xtol=0.00001, ftol=0.0001))



                    value f before changing x1 is 39.0
                    x1 is changed from 2 to 1.1447142425533319
                    value f before changing x2 is 34.5
                    x2 is changed from 3 to -1.5
                    value f before changing x3 is 14.5
                    x3 is changed from 4 to 0.5
After iteration 1, the value of f is2.5 and x = [ 1 -1  0]

                    value f before changing x1 is 2.5
                    x1 is changed from 1 to 1
                    value f before changing x2 is 2.5
                    x2 is changed from -1 to 0.5
                    value f before changing x3 is 0.5
                    x3 is changed from 0 to 0.0
After iteration 1, the value of f is0.5 and x = [1 0 0]

                    value f before changing x1 is 0.5
                    x1 is changed from 1 to 0.0
                    value f before changing x2 is 0.0
                    x2 is changed from 0 to 0.0
                    value f before changing x3 i